import { ProductCard, type MarketplaceProduct } from "@/components/MarketplaceShell";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";

export default function Catalog() {
  const [category, setCategory] = useState("All");
  const [maxPrice, setMaxPrice] = useState("all");
  const [vendor, setVendor] = useState("");
  const params = useMemo(() => ({ category: category === "All" ? undefined : category, maxPrice: maxPrice === "all" ? undefined : Number(maxPrice), vendor: vendor.trim() || undefined }), [category, maxPrice, vendor]);
  const { data: categories } = trpc.catalog.categories.useQuery();
  const { data, isLoading } = trpc.catalog.list.useQuery(params);
  const products = (data ?? []) as MarketplaceProduct[];
  return <div className="container py-12 sm:py-16"><div className="flex flex-col justify-between gap-6 border-b border-[#20241f]/15 pb-10 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#e35f36]">The full edit</p><h1 className="mt-3 font-serif text-6xl tracking-[-0.05em] sm:text-7xl">Shop all.</h1><p className="mt-4 max-w-lg text-[#77776f]">Objects, accessories, and everyday luxuries from a growing circle of independent makers.</p></div><div className="flex items-center gap-2 text-sm text-[#77776f]"><span className="font-bold text-[#20241f]">{products.length}</span> results <ArrowUpRight size={15} /></div></div><div className="my-8 grid gap-3 rounded-[1.5rem] bg-[#e8e4db] p-4 md:grid-cols-[1.1fr_1fr_1fr] md:p-5"><div className="relative"><Search size={16} className="absolute left-3 top-3 text-[#77776f]" /><Input value={vendor} onChange={event => setVendor(event.target.value)} placeholder="Search maker" className="h-10 border-0 bg-[#f6f3ee] pl-9" /></div><label className="flex items-center gap-2 rounded-md bg-[#f6f3ee] px-3 text-sm"><SlidersHorizontal size={16} className="text-[#77776f]" /><select value={category} onChange={event => setCategory(event.target.value)} className="h-10 w-full bg-transparent outline-none"><option value="All">All categories</option>{(categories ?? []).filter(item => item !== "All").map(item => <option key={item} value={item}>{item}</option>)}</select></label><select value={maxPrice} onChange={event => setMaxPrice(event.target.value)} className="h-10 rounded-md bg-[#f6f3ee] px-3 text-sm outline-none"><option value="all">Any price</option><option value="50">Under $50</option><option value="100">Under $100</option><option value="150">Under $150</option></select></div>{isLoading ? <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[1, 2, 3, 4].map(item => <div key={item} className="aspect-[4/5] animate-pulse rounded-[1.75rem] bg-[#e8e4db]" />)}</div> : products.length > 0 ? <div className="grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{products.map(product => <ProductCard key={product.id} product={product} />)}</div> : <div className="rounded-[1.75rem] bg-[#e8e4db] px-6 py-20 text-center"><h2 className="font-serif text-3xl">No exact matches yet.</h2><p className="mt-2 text-sm text-[#77776f]">Try a wider price range or clear the maker search.</p><button className="mt-6 text-sm font-bold underline underline-offset-4" onClick={() => { setCategory("All"); setMaxPrice("all"); setVendor(""); }}>Reset filters</button></div>}</div>;
}
