import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Check, PackageOpen } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

export default function VendorRegistration() {
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", description: "" });
  const application = trpc.vendors.submitApplication.useMutation({ onSuccess: () => { setSubmitted(true); toast.success("Application received"); } });
  const submit = (event: React.FormEvent) => { event.preventDefault(); application.mutate(form); };
  if (submitted) return <div className="container flex min-h-[620px] items-center justify-center py-16"><div className="max-w-lg text-center"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#d9e7d2]"><Check size={30} /></div><p className="mt-8 text-xs font-bold uppercase tracking-[0.2em] text-[#e35f36]">You’re on the list</p><h1 className="mt-3 font-serif text-6xl leading-none">Let’s make<br /><em>room.</em></h1><p className="mx-auto mt-6 max-w-md leading-7 text-[#77776f]">Thanks for telling us about your work. Our team will review your application and be in touch shortly.</p><Button asChild className="mt-8 rounded-full bg-[#20241f] px-7 hover:bg-[#e35f36]"><Link href="/catalog">Explore the marketplace <ArrowUpRight size={16} /></Link></Button></div></div>;
  return <div className="container grid min-h-[690px] gap-12 py-14 lg:grid-cols-[0.85fr_1.15fr] lg:items-center"><div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#f2c7a8]"><PackageOpen size={22} /></div><p className="mt-8 text-xs font-bold uppercase tracking-[0.2em] text-[#e35f36]">For independent makers</p><h1 className="mt-3 max-w-lg font-serif text-6xl leading-[0.9] tracking-[-0.05em] sm:text-7xl">Your work<br /><em>belongs</em> here.</h1><p className="mt-7 max-w-md text-lg leading-8 text-[#77776f]">Rijoya is a small, considered corner of the internet for products with a point of view. Tell us what you make.</p><div className="mt-10 space-y-4 text-sm"><div className="flex gap-3"><span className="font-bold text-[#e35f36]">01</span><span>Curated storefront placement</span></div><div className="flex gap-3"><span className="font-bold text-[#e35f36]">02</span><span>Simple tools for products and orders</span></div><div className="flex gap-3"><span className="font-bold text-[#e35f36]">03</span><span>Transparent 12.5% marketplace commission</span></div></div></div><form onSubmit={submit} className="rounded-[2rem] bg-[#20241f] p-7 text-[#f6f3ee] shadow-2xl shadow-[#20241f]/10 sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#d9e7d2]">Start a conversation</p><h2 className="mt-3 font-serif text-4xl">Tell us about your shop.</h2><div className="mt-8 space-y-5"><label className="block text-sm"><span className="mb-2 block text-[#f6f3ee]/70">Shop or maker name</span><Input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} className="border-white/15 bg-white/10 text-white placeholder:text-white/35" placeholder="Mara Studio" /></label><label className="block text-sm"><span className="mb-2 block text-[#f6f3ee]/70">Email address</span><Input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} className="border-white/15 bg-white/10 text-white placeholder:text-white/35" placeholder="hello@yourshop.com" /></label><label className="block text-sm"><span className="mb-2 block text-[#f6f3ee]/70">What do you make?</span><textarea required value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} className="min-h-28 w-full resize-y rounded-md border border-white/15 bg-white/10 px-3 py-2 text-sm outline-none placeholder:text-white/35 focus:border-[#d9e7d2]" placeholder="A few words about your products, materials, and point of view..." /></label></div><Button type="submit" disabled={application.isPending} className="mt-8 h-12 w-full rounded-full bg-[#f2a88f] font-bold text-[#20241f] hover:bg-white">{application.isPending ? "Sending application..." : "Submit application"} <ArrowUpRight size={16} /></Button><p className="mt-4 text-center text-xs text-white/40">We review every application by hand.</p></form></div>;
}
